#!/usr/bin/env bash
# This is a script that display "Best School" 10 times but on the 9th iteration displays "Hi"
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	(( x++ ))
done
