#!/usr/bin/env bash
# This displays time hours and minutes
hour=0
min=0
while [[ "$hour" -lt 13 ]]; do
	echo "Hour: $hour"
	while [[ "$min" -lt 60 ]]; do
		echo "$min"
		((min++))
	done
	min=0
	((hour++))
done 
